### ISSUE TITLE
LambdaESCognitoRole referring to commercial cloud instead of govcloud

### ISSUE THREAD

**Issue by theghaazi** [aws-solutions/aws-centralized-logging#23]
Getting this error when trying to deploy the code in govcloud. the arn is in correct and should say aws-us-gov insted.

LambdaESCognitoRole |-- |--Partition "aws" is not valid for resource "arn:**aws**:cognito-idp:us-gov-west-1:111111111111:userpool/us-gov-west-1_TiyiDL8Y4". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: b8a67e60-2c72-4478-97f0-2fd86e020b4a)

**Comment by rakshb** [comment]
Hello @theghaazi  The solution currently doesn't support Gov Cloud regions. I'm adding this as a backlog item for a future release. Thank you
