### ISSUE TITLE
Can't use email with '+' addressing for AdminEmail parameter

### ISSUE THREAD

**Issue by milbrya** [aws-solutions/aws-centralized-logging#27]
**Describe the bug**

If I use and e-mail address with xxxx+yyyy@zzz.com, it template fails to launch with the error message: Parameter 'AdminEmail' must match pattern ^[\w]+\@[\w]+\.[a-z]+$

**To Reproduce**

Enter an e-mail address that has the plus addressing scheme

**Expected behavior**

I would expect '+' addressing in the e-mail address for AdminEmail.

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.0.0]

(SO0009) - The AWS CloudFormation template for deployment of the centralized-logging. Version v4.0.0",

- us-east-1
- No

**Comment by gsingh04** [comment]
Thanks for reporting this bug.

We have added it to our backlog items to be shipped with next release.

**Comment by albertogalinari** [comment]
Any solution or update regarding this issue ? Iam facing the same problem and cannot deploy cloudformation.

**Comment by alkayahan** [comment]
@alb777 until my PR is reviewed, you can try from my fork where I fixed this problem https://github.com/alkayahan/aws-centralized-logging/tree/bugfix-emailregex

**Comment by gsingh04** [comment]
This has been addressed with release v4.0.1
