### ISSUE TITLE
Nodejs10.x is no longer supported

### ISSUE THREAD

**Issue by rprentyaws** [aws-solutions/aws-centralized-logging#39]
**Describe the bug**

Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs14.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 8dcaaf90-1fb5-40db-8725-a7d08e20b960, Extended Request ID: null)" (RequestToken: 0a868f2c-3a64-d202-71a1-bb8dcfe0c7f1, HandlerErrorCode: InvalidRequest)

The Lambda function with the name "HelperProviderframeworkonEvent1079DE9D" has runtime version nodejs10.x. 

**To Reproduce**

[Follow step 1](https://docs.aws.amazon.com/solutions/latest/centralized-logging/deployment.html#step-1).

**Expected behavior**

**Please complete the following information about the solution:**

- [ ] Version: 4.0.0
- [ ] Region: eu-west-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs? [How to enable debug mode?](https://docs.aws.amazon.com/solutions/latest/centralized-logging/appendix-d.html)

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by gsingh04** [comment]
Thanks for reporting the issue, we are aware of this. The fix is currently being tested internally and will be going out soon.

**Comment by gsingh04** [comment]
This has been addressed with release v4.0.1
