### ISSUE TITLE
Limit the number of events sent to firehose.putRecordBatch to 500

### ISSUE THREAD

**Issue by rostskadat** [aws-solutions/aws-centralized-logging#50]
**Describe the bug**

According to [API_PutRecordBatch](https://docs.aws.amazon.com/firehose/latest/APIReference/API_PutRecordBatch.html) only 500 events can be sent simultaneously. However in case of a spike of events within the Kinesis Stream, we might receive more than 500 events. Thus the call fails, events are not consumed and the stream starts to lag behind.

**To Reproduce**

Send a spike of events simultaneously.

**Expected behavior**

We should chunk the incoming events into batches of 500 max.

**Please complete the following information about the solution:**

- [v4.0.2]
- [eu-central-1]
- [no] Was the solution modified from the version published on this repository?
- [na] If the answer to the previous question was yes, are the changes available on GitHub?
- [yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [yes] Were there any errors in the CloudWatch Logs? [How to enable debug mode?](https://docs.aws.amazon.com/solutions/latest/centralized-logging/appendix-d.html)

**Screenshots**
The following screenshot shows how the Stream get filled up.
![image](https://user-images.githubusercontent.com/6322482/229127649-d36db8ce-a799-4936-b286-0118055a5a89.png)

And this is the error in CloudWatch:
![image](https://user-images.githubusercontent.com/6322482/229128064-38991177-042c-47fa-85f3-12b39d96fc38.png)

**Additional context**
NA

**Comment by ugurcancaykara** [comment]
Getting same results at cloudwatch, can we get an update for this error ASAP ?

**Comment by morjoan** [comment]
Hi, thanks for reaching out. This solution is being EOL and will only be receiving critical patches. We recently launched the [Centralized Logging with OpenSearch](https://aws.amazon.com/solutions/implementations/centralized-logging-with-opensearch/) solution and recommend migrating to this new solution.

**Comment by abe-aws** [comment]
fixed in https://github.com/aws-solutions/aws-centralized-logging/pull/57
